CREATE DATABASE IF NOT EXISTS test_db;
USE test_db;
CREATE TABLE IF NOT EXISTS `test_db`.`Bookkeeping` ( `OrderID` INT NOT NULL AUTO_INCREMENT , `Security` TINYTEXT NOT NULL , `Qty` INT NOT NULL , `Price` DECIMAL NOT NULL , `Operation` TINYTEXT NOT NULL , `Side` TINYTEXT NOT NULL , `UserID` INT NOT NULL , PRIMARY KEY (`OrderID`)) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `test_db`.`Exchange` ( `Security` TINYTEXT NOT NULL , `UserID` INT NOT NULL , `Price` DECIMAL NOT NULL , `Qty` INT NOT NULL ) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `test_db`.`Matches` ( `Security` TINYTEXT NOT NULL , `Seller` INT NOT NULL , `Buyer` INT NOT NULL , `Qty` INT NOT NULL , `Price` DECIMAL NOT NULL ) ENGINE = InnoDB;